package ca.mcgill.ecse428.CourseChamp.model;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;

/**
 * Class that is part of the domain model of the CourseChamp System
 * This class contains information related to review tagtypes
 * 
 * A major part of this class is auto-generated by umple
 * This class is also JPA anotated for ORM
 */
@Entity
public class TagType {

  // ------------------------
  // MEMBER VARIABLES
  // ------------------------

  // TagType Attributes
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int id;
  private String description;

  // ------------------------
  // CONSTRUCTOR
  // ------------------------
  public TagType() {
  }

  public TagType(int aId, String aDescription) {
    id = aId;
    description = aDescription;
  }

  // ------------------------
  // INTERFACE
  // ------------------------

  public boolean setId(int aId) {
    boolean wasSet = false;
    id = aId;
    wasSet = true;
    return wasSet;
  }

  public boolean setDescription(String aDescription) {
    boolean wasSet = false;
    description = aDescription;
    wasSet = true;
    return wasSet;
  }

  public int getId() {
    return id;
  }

  public String getDescription() {
    return description;
  }

  public void delete() {
  }

  public String toString() {
    return super.toString() + "[" +
        "id" + ":" + getId() + "," +
        "description" + ":" + getDescription() + "]";
  }
}